apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Values.deployment.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}-{{ .Values.deployment.name }}
    app: {{ .Values.deployment.name }}
spec:
  replicas: {{ .Values.deployment.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Release.Name }}-{{ .Values.deployment.name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Release.Name }}-{{ .Values.deployment.name }}
        app: {{ .Values.deployment.name }}
        app: {{ .Values.deployment.name }}
        date: "{{ .Release.Time.Seconds }}"
    spec:
      {{- if .Values.deployment.hostAlias }}
      hostAliases:
      - ip: {{ .Values.deployment.hostAlias.sso.ip }}
        hostnames:
        - {{ .Values.deployment.hostAlias.sso.hostName }}
      - ip: {{ .Values.deployment.hostAlias.cust360.ip }}
        hostnames:
        - {{ .Values.deployment.hostAlias.cust360.hostName }}
      {{- end }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.deployment.image.name }}:{{ .Values.deployment.image.tag }}"
        command: ["java"]
        args:
          - -Djava.security.egd=file:/dev/./urandom
          - -Dspring.metrics.servo.enabled=false
          {{- if .Values.deployment.resources }}
          - -Xms{{ .Values.deployment.resources.requests.javaHeap }}
          - -Xmx{{ .Values.deployment.resources.requests.javaHeap }}
          {{- end }}
          - -jar
          - app.jar
        {{- if .Values.deployment.resources }}
        resources:
          requests:
            cpu: {{ .Values.deployment.resources.requests.cpu }}
            memory: {{ .Values.deployment.resources.requests.memory }}
          limits:
            cpu: {{ .Values.deployment.resources.limits.cpu }}
            memory: {{ .Values.deployment.resources.limits.memory }}
        {{- end }}
        imagePullPolicy: {{ .Values.deployment.image.pullPolicy }}
        ports:
        - name: {{ .Values.deployment.ports.name1 }}
          containerPort: {{ .Values.deployment.ports.containerPort1 }}
        readinessProbe:
          httpGet:
            path: {{ .Values.deployment.readinessProbe.httpGet.path }}
            port: {{ .Values.deployment.readinessProbe.httpGet.port }}
          initialDelaySeconds: {{ .Values.deployment.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.deployment.readinessProbe.periodSeconds }}
        livenessProbe:
          httpGet:
            path: {{ .Values.deployment.livenessProbe.httpGet.path }}
            port: {{ .Values.deployment.livenessProbe.httpGet.port }}
          initialDelaySeconds: {{ .Values.deployment.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.deployment.livenessProbe.periodSeconds }}
        env:
          - name: CONNECTION_TIME_OUT
            valueFrom:
              configMapKeyRef:
                name: {{ .Release.Name }}-{{ .Values.configMap.name }}
                key: connectionTimeOut
          - name: SOCKET_TIME_OUT
            valueFrom:
              configMapKeyRef:
                name: {{ .Release.Name }}-{{ .Values.configMap.name }}
                key: socketTimeOut
          - name: RETRY_TIME_OUT
            valueFrom:
              configMapKeyRef:
                name: {{ .Release.Name }}-{{ .Values.configMap.name }}
                key: retryTimeOut
          - name: ELASTIC_HOST
            valueFrom:
              configMapKeyRef:
                name: {{ .Release.Name }}-{{ .Values.configMap.name }}
                key: elasticHost
          - name: ELASTIC_PORT
            valueFrom:
              configMapKeyRef:
                name: {{ .Release.Name }}-{{ .Values.configMap.name }}
                key: elasticPort
          - name: FIELD_MATCH_CONFIGURATION
            valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-{{ .Values.configMap.name }}
                  key: fieldMatchConfiguration
          - name: RESTRICTED_FIELD_MATCH_CONFIGURATION
            valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-{{ .Values.configMap.name }}
                  key: restrictedFieldMatchConfiguration
          - name: ENCRYPTION_KEY
            valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-{{ .Values.secret.name }}
                  key: aes_secret_key
          - name: MAXIMUM_LIMIT_TO_SEARCH
            valueFrom:
              configMapKeyRef:
                name: {{ .Release.Name }}-{{ .Values.configMap.name }}
                key: maxLimitToSearch
          - name: GNY_CUST_SEARCH
            valueFrom:
              configMapKeyRef:
                name: {{ .Release.Name }}-{{ .Values.configMap.name }}
                key: gnyCustSearch
          - name: GNY_CUST_DOC
            valueFrom:
              configMapKeyRef:
                name: {{ .Release.Name }}-{{ .Values.configMap.name }}
                key: gnyCustDoc
          - name: GNY_HRIS_MASTER
            valueFrom:
              configMapKeyRef:
                name: {{ .Release.Name }}-{{ .Values.configMap.name }}
                key: gnyHrisMaster
          - name: GNY_HRIS_DOC
            valueFrom:
              configMapKeyRef:
                name: {{ .Release.Name }}-{{ .Values.configMap.name }}
                key: gnyHrisDoc
          - name: GNY_ACCTCUST_REF
            valueFrom:
              configMapKeyRef:
                name: {{ .Release.Name }}-{{ .Values.configMap.name }}
                key: gnyAcctCustRef
          - name: GNY_ACCTCUST_REF_DOC
            valueFrom:
              configMapKeyRef:
                name: {{ .Release.Name }}-{{ .Values.configMap.name }}
                key: gnyAcctCustRefDoc
          - name: AUTH_SERVER_SERVICE
            valueFrom:
              configMapKeyRef:
                name: {{ .Release.Name }}-{{ .Values.configMap.name }}
                key: authServerService
          - name: YBL_MS_REALM
            valueFrom:
              configMapKeyRef:
                name: {{ .Release.Name }}-{{ .Values.configMap.name }}
                key: yblMsRealm
          - name: MS_CLIENT_ID
            valueFrom:
              configMapKeyRef:
                name: {{ .Release.Name }}-{{ .Values.configMap.name }}
                key: msClientId
          - name: LOGGING_LEVEL_ROOT
            valueFrom:
              configMapKeyRef:
                name: {{ .Release.Name }}-{{ .Values.configMap.name }}
                key: loggingLevelRoot
          - name: USER_NAME
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}-{{ .Values.secret.name }}
                key: userName
          - name: PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}-{{ .Values.secret.name }}
                key: password
          - name: ELASTIC_LOGGING_LEVEL
            valueFrom:
              configMapKeyRef:
                name: {{ .Release.Name }}-{{ .Values.configMap.name }}
                key: elastic_logging_level
          - name: FIELD_QUERY_MAPPING
            valueFrom:
              configMapKeyRef:
                name: {{ .Release.Name }}-{{ .Values.configMap.name }}
                key: fieldQueryMapping
          - name: DEFAULT_SORT_FIELD
            valueFrom:
              configMapKeyRef:
                name: {{ .Release.Name }}-{{ .Values.configMap.name }}
                key: defaultSortField
          - name: DEFAULT_SORT_ORDER
            valueFrom:
              configMapKeyRef:
                name: {{ .Release.Name }}-{{ .Values.configMap.name }}
                key: defaultSortOrder
