apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-{{ .Values.secret.name }}
  namespace: {{ .Values.namespace }}
data:
  aes_secret_key: {{ .Values.secret.aes_secret_key }}
  userName: {{ .Values.secret.userName }}
  password: {{ .Values.secret.password }}