apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-{{ .Values.configMap.name }}
  namespace: {{ .Values.namespace }}
data:
  elasticHost: {{ .Values.configMap.elasticHost }}
  elasticPort: {{ .Values.configMap.elasticPort }}
  connectionTimeOut: {{ .Values.configMap.connectionTimeOut }}
  socketTimeOut: {{ .Values.configMap.socketTimeOut }}
  retryTimeOut: {{ .Values.configMap.retryTimeOut }}
  badInputMessage: Search input is not in correct format!
  authServerService: {{ .Values.configMap.authServerService }}
  yblMsRealm: {{ .Values.configMap.yblMsRealm }}
  msClientId: {{ .Values.configMap.msClientId }}
  maxLimitToSearch: {{ .Values.configMap.maxLimitToSearch }}
  gnyEntityMapper: {{ .Values.configMap.gnyEntMapper }}
  gnyEntityMaster: {{ .Values.configMap.gnyEntMaster }}
  loggingLevelRoot: {{ .Values.configMap.loggingLevelRoot}}
  elastic_logging_level: {{ .Values.configMap.elasticLoggingLevel}}
  fieldQueryMapping: '{{ .Values.configMap.fieldQueryMapping}}'
  defaultSortField: {{ .Values.configMap.defaultSortField}}
  defaultSortOrder: {{ .Values.configMap.defaultSortOrder}}
