apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Release.Name }}-{{ .Values.service.name }}
spec:
  hosts:
  - {{ .Values.virtualService.host1 }}
  gateways:
  - {{ .Values.virtualService.gateway1 }}
  http:
  - match:
    - uri:
        prefix: {{ .Values.virtualService.uri1 }}
    route:
    - destination:
        port:
          number: 80
        host: {{ .Release.Name }}-{{ .Values.service.name }}.{{ .Values.namespace }}.svc.{{ .Values.virtualService.clusterName }}
