
apiVersion: v1
kind: Service
metadata:
  name: entity-search
  namespace: genie-ms
  labels:
    app: entity-search
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: entity-search
  type: ClusterIP
      