version: aplha
namespace: genie-ms
deployment:
  name: entity-search
  replicaCount: 1
  image:
    name: ybalx1v316dwh03.yesbank.com:6443/entity-search
    tag: latest
    pullPolicy: IfNotPresent
  ports:
    name1: http
    containerPort1: 8080
  readinessProbe:
    httpGet:
      path: /actuator/health
      port: 8080
    initialDelaySeconds: 15
    periodSeconds: 10
  livenessProbe:
    httpGet:
      path: /actuator/health
      port: 8080
    initialDelaySeconds: 30
    periodSeconds: 30

service:
  name: entity-search
  type: ClusterIP
  port: 80
  targetPort: 8080
  portName: http


configMap:
  name: search-config
  elasticHost: elastic-service.default.svc.cluster.local
  elasticPort: "'9200'"
  connectionTimeOut: "'6000'"
  socketTimeOut: "'60000'"
  retryTimeOut: "'60000'"
  badInputMessage: Search input is not in correct format!
  authServerService: https://sso.uat-genie.yesbank.in
  yblMsRealm: YBL_MS_REALM
  msClientId: genie-backend
  maxLimitToSearch: "'200'"
  loggingLevelRoot: INFO
  elasticLoggingLevel: INFO
  defaultSortField: cust_open_date
  defaultSortOrder: DESC
  gnyEntMapper:
  gnyEntMaster:

virtualService:
  clusterName: cluster.local
  name: entity-search
  uri1: /api/entity/search
  host1: ms.uat-genie.yesbank.in
  gateway1: https-gateway
  route:
    destination1:
      port:
        number: 80

secret:
  name: aes-secret
  aes_secret_key: eWVzYmFua2R3aDE4MTkyMA==
  userName: ZWxhc3RpYw==
  password: YXBwbGVAMTIz

autoscaler:
  name: entity-search-as
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 60

monitoring:
  namespace: monitoring
  interval:  30s
  port: http
  path: /actuator/prometheus
  jobLabel: springboot