apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: entity-search
spec:
  hosts:
  - "*"
  gateways:
  - http-gateway
  http:
  - match:
    - uri:
        prefix: /api/entity/
    route:
    - destination:
        port:
          number: 80
        host: customer-search.genie-ms.svc.cluster.local
